agents:
  queue: kibana-default

steps:
    # It's easier to do this through a required env var, than an input.
    #  Inputs are not accessible in the pipeline code,
    #  so you'd have to get a script to dig up the meta-data, then emit a build step to buildkite
  - label: "Ensure required ENV variable ES_SERVERLESS_IMAGE"
    if: "build.env('ES_SERVERLESS_IMAGE') == null"
    command: |
      echo "Please provide the env variable ES_SERVERLESS_IMAGE for the build."
      buildkite-agent annotate --style error "Missing environment variable ES_SERVERLESS_IMAGE"
      exit 1

  - wait: ~

  - label: ":pipeline: (:kibana: x :elastic:) Trigger Kibana Serverless suite"
    trigger: "kibana-serverless"
    if: "build.env('SKIP_VERIFICATION') != '1' && build.env('SKIP_VERIFICATION') != 'true'"
    build:
      commit: ${BUILDKITE_COMMIT}
      branch: ${BUILDKITE_BRANCH}
      env:
        TEST_ES_SERVERLESS_IMAGE: ${ES_SERVERLESS_IMAGE}

  - wait: ~

  - label: ":arrow_up::elastic::arrow_up: Promote docker image"
    command: .buildkite/scripts/steps/es_snapshots/promote_es_serverless_image.sh $ES_SERVERLESS_IMAGE
